#!/bin/bash
#
# Run rake before pushing commits
#

bundle exec rake

if [ $? -ne 0 ]; then
    printf "\n\n\n\e[31m"
    printf "     ======================================================\n"
    printf "     ERROR: The default rake task failed. Aborting git push\n"
    printf "     ======================================================\n"
    printf "\n\n\e[0m"

    exit 1
fi

