require: rubocop-performance

AllCops:
  NewCops: enable
  TargetRubyVersion: 2.7

Metrics/BlockLength:
  Exclude:
    - "Rakefile"
    - "**/*.rake"
    - "**/*.gemspec"
    - "spec/**/*spec.rb"

Metrics/ClassLength:
  Max: 150

Layout/LineLength:
  Max: 98
  IgnoreCopDirectives: true

Metrics/MethodLength:
  Max: 25

Style/FrozenStringLiteralComment:
  Enabled: false

Style/Documentation:
  Enabled: false
