plugins: rubocop-performance

AllCops:
  NewCops: enable
  TargetRubyVersion: 4.0
  SuggestExtensions: false

Metrics/BlockLength:
  Exclude:
    - "Rakefile"
    - "**/*.rake"
    - "**/*.gemspec"
    - "spec/**/*spec.rb"

Metrics/ClassLength:
  Max: 150

Layout/LineLength:
  Max: 98
  AllowCopDirectives: true

Metrics/MethodLength:
  Max: 25

Style/FrozenStringLiteralComment:
  Enabled: false

Style/Documentation:
  Enabled: false

Gemspec/DevelopmentDependencies:
  Enabled: false

Lint/ConstantDefinitionInBlock:
  Exclude:
    - "spec/**/*"
