require: rubocop-performance

AllCops:
  TargetRubyVersion: 2.6

Metrics/BlockLength:
  Exclude:
    - "Rakefile"
    - "**/*.rake"
    - "**/*.gemspec"
    - "spec/**/*spec.rb"

Metrics/LineLength:
  Max: 98
  IgnoreCopDirectives: true

Style/FrozenStringLiteralComment:
  Enabled: false

Style/Documentation:
  Enabled: false
